# Site settings
title: Kajetan Puchalski
email: kajetan.puchalski@tuta.io
url: https://mrkajetanp.github.io

description: "Freelance Mobile and Full Stack Web Developer & Software Engineering student based in Glasgow, Scotland. I deliver high-quality mobile and web applications."

keywords: "Kajetan, Puchalski, Freelance, Software, Engineer, Full, Stack, Back, Front, End, Mobile, Android, iOS"
skills: "Software Engineer - Mobile Developer - Full Stack Developer"
meta_author: Puchalski Kajetan

# Google webmaster tools
google_verify: Suzv_HfNM6ibEZ8rBqQG9YJ4lOlqi0cfPoINJYtx2js

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  # Picture background
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  # Top bar
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Kajetan Puchalski
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Glasgow
  - line: Scotland
  - line: United Kingdom

# Credits content
credits: 'Freelancer theme by <a href="http://startbootstrap.com">Start Bootstrap</a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
